spring:
  datasource:
    username: postgres
    password: lol
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://structuremade.de:5432/structuremade
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      maximum-pool-size: 4
      max-lifetime: 1800000
  jpa:
    show-sql: off
    generate-ddl: off
    properties:
      hibernate:
        default_schema: services
    hibernate:
      ddl-auto: validate
  application:
    name: VERIFYSERVICE
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: https://eureka.structuremade.de/eureka/
server:
  port: 80
